name: oleazara
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: "0.11.3+17"
  url_launcher:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.jpg"

  flutter_icons:
    android: true
    ios: true
    image_path: "images/instagram.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/logo.jpg
   - images/instagram.png
   - images/imageninicio.jpeg
   - images/youtube.jpeg
   - images/facebook.png


  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Tomorrow
      fonts:
        - asset: fonts/Tomorrow-Black.ttf
        - asset: fonts/Tomorrow-BlackItalic.ttf
        - asset: fonts/Tomorrow-Bold.ttf
        - asset: fonts/Tomorrow-BoldItalic.ttf
        - asset: fonts/Tomorrow-Italic.ttf
        - asset: fonts/Tomorrow-Regular.ttf
          style: italic
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Black.ttf
        - asset: fonts/Raleway-BlackItalic.ttf
        - asset: fonts/Raleway-Bold.ttf
        - asset: fonts/Raleway-BoldItalic.ttf
        - asset: fonts/Raleway-Italic.ttf
        - asset: fonts/Raleway-Regular.ttf
    - family: SairaSemiCondensed
      fonts:
        - asset: fonts/SairaSemiCondensed-Black.ttf
        - asset: fonts/SairaSemiCondensed-Bold.ttf
        - asset: fonts/SairaSemiCondensed-Regular.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
